# Etapa de construcción
FROM openjdk:21 AS build
WORKDIR /app
COPY . .
RUN ./mvnw clean package -DskipTests

# Etapa de ejecución
FROM eclipse-temurin:21-jre
WORKDIR /app
COPY --from=build /app/target/spring-boot-api-almacenes-ardilla-0.0.1-SNAPSHOT.jar spring-boot-api-almacenes-ardilla-0.0.1-SNAPSHOT.jar
EXPOSE 8080
ENTRYPOINT ["java", "-jar", "/spring-boot-api-almacenes-ardilla-0.0.1-SNAPSHOT.jar"]