insert into A_TIPO_PRODUCTO (nombre) values ('Food - Condiments');
insert into A_TIPO_PRODUCTO (nombre) values ('Outdoor');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Dairy');
insert into A_TIPO_PRODUCTO (nombre) values ('Outdoor');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Snacks');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Baking');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Soups');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Condiments');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Snacks');
insert into A_TIPO_PRODUCTO (nombre) values ('Home');
insert into A_TIPO_PRODUCTO (nombre) values ('Home');
insert into A_TIPO_PRODUCTO (nombre) values ('Accessories');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Seafood');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Prepared Meals');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Snacks');
insert into A_TIPO_PRODUCTO (nombre) values ('Fitness');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Dairy');
insert into A_TIPO_PRODUCTO (nombre) values ('Sports');
insert into A_TIPO_PRODUCTO (nombre) values ('Home');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Bread');
insert into A_TIPO_PRODUCTO (nombre) values ('Clothing - Dresses');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Condiments');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Deli');
insert into A_TIPO_PRODUCTO (nombre) values ('Grooming');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Meat Alternatives');
insert into A_TIPO_PRODUCTO (nombre) values ('Garden');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Grains');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Beverages');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Produce');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Marinades');
insert into A_TIPO_PRODUCTO (nombre) values ('Home');
insert into A_TIPO_PRODUCTO (nombre) values ('Safety');
insert into A_TIPO_PRODUCTO (nombre) values ('Pets');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Pasta');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Frozen Foods');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Frozen Meals');
insert into A_TIPO_PRODUCTO (nombre) values ('Clothing - Accessories');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Breakfast');
insert into A_TIPO_PRODUCTO (nombre) values ('Outdoor');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Breakfast');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Snacks');
insert into A_TIPO_PRODUCTO (nombre) values ('Accessories');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Bakery');
insert into A_TIPO_PRODUCTO (nombre) values ('Electronics');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Grains');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Fruits');
insert into A_TIPO_PRODUCTO (nombre) values ('Outdoor');
insert into A_TIPO_PRODUCTO (nombre) values ('Outdoor');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Grains');
insert into A_TIPO_PRODUCTO (nombre) values ('Smart Home');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Snacks');
insert into A_TIPO_PRODUCTO (nombre) values ('Kitchen');
insert into A_TIPO_PRODUCTO (nombre) values ('Accessories');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Meat');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Canned Goods');
insert into A_TIPO_PRODUCTO (nombre) values ('Travel');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Produce');
insert into A_TIPO_PRODUCTO (nombre) values ('Audio');
insert into A_TIPO_PRODUCTO (nombre) values ('Automotive');
insert into A_TIPO_PRODUCTO (nombre) values ('Pets');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Dairy');
insert into A_TIPO_PRODUCTO (nombre) values ('Kitchen');
insert into A_TIPO_PRODUCTO (nombre) values ('Kitchen');
insert into A_TIPO_PRODUCTO (nombre) values ('Pets');
insert into A_TIPO_PRODUCTO (nombre) values ('Clothing - Accessories');
insert into A_TIPO_PRODUCTO (nombre) values ('Safety');
insert into A_TIPO_PRODUCTO (nombre) values ('Clothing - Shirts');
insert into A_TIPO_PRODUCTO (nombre) values ('Clothing');
insert into A_TIPO_PRODUCTO (nombre) values ('Home');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Condiments');
insert into A_TIPO_PRODUCTO (nombre) values ('Outdoor');
insert into A_TIPO_PRODUCTO (nombre) values ('Clothing - Activewear');
insert into A_TIPO_PRODUCTO (nombre) values ('Food');
insert into A_TIPO_PRODUCTO (nombre) values ('Outdoor');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Frozen Desserts');
insert into A_TIPO_PRODUCTO (nombre) values ('Pets');
insert into A_TIPO_PRODUCTO (nombre) values ('Automotive');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Breakfast');
insert into A_TIPO_PRODUCTO (nombre) values ('Toys');
insert into A_TIPO_PRODUCTO (nombre) values ('Clothing - Tops');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Snacks');
insert into A_TIPO_PRODUCTO (nombre) values ('Clothing');
insert into A_TIPO_PRODUCTO (nombre) values ('Pets');
insert into A_TIPO_PRODUCTO (nombre) values ('Books');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Dairy');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Spices');
insert into A_TIPO_PRODUCTO (nombre) values ('Fitness');
insert into A_TIPO_PRODUCTO (nombre) values ('Kitchen');
insert into A_TIPO_PRODUCTO (nombre) values ('Kitchen');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Snacks');
insert into A_TIPO_PRODUCTO (nombre) values ('Fitness');
insert into A_TIPO_PRODUCTO (nombre) values ('Pets');
insert into A_TIPO_PRODUCTO (nombre) values ('Outdoor');
insert into A_TIPO_PRODUCTO (nombre) values ('Garden');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Bakery');
insert into A_TIPO_PRODUCTO (nombre) values ('Fitness');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Snacks');
insert into A_TIPO_PRODUCTO (nombre) values ('Kitchen');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Frozen');
insert into A_TIPO_PRODUCTO (nombre) values ('Kitchen');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Sides');
insert into A_TIPO_PRODUCTO (nombre) values ('Travel');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Sides');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Frozen Foods');
insert into A_TIPO_PRODUCTO (nombre) values ('Home');
insert into A_TIPO_PRODUCTO (nombre) values ('Kitchen');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Canned Goods');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Desserts');
insert into A_TIPO_PRODUCTO (nombre) values ('Toys');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Vegetable');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Snacks');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Condiments');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Condiments');
insert into A_TIPO_PRODUCTO (nombre) values ('Pets');
insert into A_TIPO_PRODUCTO (nombre) values ('Health');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Condiments');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Snacks');
insert into A_TIPO_PRODUCTO (nombre) values ('Office');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Fruits');
insert into A_TIPO_PRODUCTO (nombre) values ('Pets');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Grains');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Cereal');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Frozen');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Condiments');
insert into A_TIPO_PRODUCTO (nombre) values ('Storage');
insert into A_TIPO_PRODUCTO (nombre) values ('Garden');
insert into A_TIPO_PRODUCTO (nombre) values ('Garden');
insert into A_TIPO_PRODUCTO (nombre) values ('Kitchen');
insert into A_TIPO_PRODUCTO (nombre) values ('Kitchen');
insert into A_TIPO_PRODUCTO (nombre) values ('Books');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Sauces');
insert into A_TIPO_PRODUCTO (nombre) values ('Pets');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Bakery');
insert into A_TIPO_PRODUCTO (nombre) values ('Toys');
insert into A_TIPO_PRODUCTO (nombre) values ('Automotive');
insert into A_TIPO_PRODUCTO (nombre) values ('Accessories');
insert into A_TIPO_PRODUCTO (nombre) values ('Clothing - Shirts');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Snacks');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Sides');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Bakery');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Frozen Foods');
insert into A_TIPO_PRODUCTO (nombre) values ('Clothing - Outerwear');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Snacks');
insert into A_TIPO_PRODUCTO (nombre) values ('Accessories');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Baking');
insert into A_TIPO_PRODUCTO (nombre) values ('Accessories');
insert into A_TIPO_PRODUCTO (nombre) values ('Pets');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Dips');
insert into A_TIPO_PRODUCTO (nombre) values ('Fitness');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Snacks');
insert into A_TIPO_PRODUCTO (nombre) values ('Clothing - Bottoms');
insert into A_TIPO_PRODUCTO (nombre) values ('Automotive');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Beverages');
insert into A_TIPO_PRODUCTO (nombre) values ('Pets');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Meats');
insert into A_TIPO_PRODUCTO (nombre) values ('Office');
insert into A_TIPO_PRODUCTO (nombre) values ('Toys');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Salads');
insert into A_TIPO_PRODUCTO (nombre) values ('Clothing - Outerwear');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Seafood');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Produce');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Dairy Alternatives');
insert into A_TIPO_PRODUCTO (nombre) values ('Kitchen');
insert into A_TIPO_PRODUCTO (nombre) values ('Kitchen');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Vegetables');
insert into A_TIPO_PRODUCTO (nombre) values ('Pets');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Condiments');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Breakfast');
insert into A_TIPO_PRODUCTO (nombre) values ('Accessories');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Seafood');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Frozen Food');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Condiments');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Soups');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Snacks');
insert into A_TIPO_PRODUCTO (nombre) values ('Clothing - Shoes');
insert into A_TIPO_PRODUCTO (nombre) values ('Home');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Snacks');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Frozen Foods');
insert into A_TIPO_PRODUCTO (nombre) values ('Health');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Condiments');
insert into A_TIPO_PRODUCTO (nombre) values ('Accessories');
insert into A_TIPO_PRODUCTO (nombre) values ('Kitchen');
insert into A_TIPO_PRODUCTO (nombre) values ('Food');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Frozen Foods');
insert into A_TIPO_PRODUCTO (nombre) values ('Electronics');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Prepared Foods');
insert into A_TIPO_PRODUCTO (nombre) values ('Health');
insert into A_TIPO_PRODUCTO (nombre) values ('Kitchen');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Snacks');
insert into A_TIPO_PRODUCTO (nombre) values ('Outdoor');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Snacks');
insert into A_TIPO_PRODUCTO (nombre) values ('Health');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Seafood');
insert into A_TIPO_PRODUCTO (nombre) values ('Clothing - Tops');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Bakery');
insert into A_TIPO_PRODUCTO (nombre) values ('Health');
insert into A_TIPO_PRODUCTO (nombre) values ('Accessories');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Condiments');
insert into A_TIPO_PRODUCTO (nombre) values ('Outdoor');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Snacks');
insert into A_TIPO_PRODUCTO (nombre) values ('Toys');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Beverages');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Snacks');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Snacks');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Snacks');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Sauces');
insert into A_TIPO_PRODUCTO (nombre) values ('Clothing - Dresses');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Frozen Foods');
insert into A_TIPO_PRODUCTO (nombre) values ('Electronics');
insert into A_TIPO_PRODUCTO (nombre) values ('Office');
insert into A_TIPO_PRODUCTO (nombre) values ('Clothing - Shirts');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Snacks');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Snacks');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Baking Goods');
insert into A_TIPO_PRODUCTO (nombre) values ('Crafts');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Grains');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Produce');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Frozen Foods');
insert into A_TIPO_PRODUCTO (nombre) values ('Clothing - Tops');
insert into A_TIPO_PRODUCTO (nombre) values ('Outdoor');
insert into A_TIPO_PRODUCTO (nombre) values ('Outdoor');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Breakfast');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Snacks');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Prepared Meals');
insert into A_TIPO_PRODUCTO (nombre) values ('Kitchen');
insert into A_TIPO_PRODUCTO (nombre) values ('Health');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Breakfast');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Grains');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Grains');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Meats');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Snacks');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Beverages');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Baking Goods');
insert into A_TIPO_PRODUCTO (nombre) values ('Health');
insert into A_TIPO_PRODUCTO (nombre) values ('Outdoor');
insert into A_TIPO_PRODUCTO (nombre) values ('Outdoor');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Sauces');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Oils & Vinegars');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Condiments');
insert into A_TIPO_PRODUCTO (nombre) values ('Home Improvement');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Produce');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Snacks');
insert into A_TIPO_PRODUCTO (nombre) values ('Kitchen');
insert into A_TIPO_PRODUCTO (nombre) values ('Kitchen');
insert into A_TIPO_PRODUCTO (nombre) values ('Kitchen');
insert into A_TIPO_PRODUCTO (nombre) values ('Outdoor');
insert into A_TIPO_PRODUCTO (nombre) values ('Kitchen');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Canned Goods');
insert into A_TIPO_PRODUCTO (nombre) values ('Accessories');
insert into A_TIPO_PRODUCTO (nombre) values ('Office');
insert into A_TIPO_PRODUCTO (nombre) values ('Kitchen');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Canned Goods');
insert into A_TIPO_PRODUCTO (nombre) values ('Home');
insert into A_TIPO_PRODUCTO (nombre) values ('Kitchen');
insert into A_TIPO_PRODUCTO (nombre) values ('Automotive');
insert into A_TIPO_PRODUCTO (nombre) values ('Health');
insert into A_TIPO_PRODUCTO (nombre) values ('Pets');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Frozen Foods');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Cereal');
insert into A_TIPO_PRODUCTO (nombre) values ('Kitchen');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Snacks');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Seafood');
insert into A_TIPO_PRODUCTO (nombre) values ('Outdoor');
insert into A_TIPO_PRODUCTO (nombre) values ('Tools');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Frozen Foods');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Pasta');
insert into A_TIPO_PRODUCTO (nombre) values ('Outdoor');
insert into A_TIPO_PRODUCTO (nombre) values ('Home');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Snacks');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Frozen Foods');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Beverages');
insert into A_TIPO_PRODUCTO (nombre) values ('Travel');
insert into A_TIPO_PRODUCTO (nombre) values ('Outdoor');
insert into A_TIPO_PRODUCTO (nombre) values ('Kitchen');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Canned Goods');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Snacks');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Baking & Cooking');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Dips');
insert into A_TIPO_PRODUCTO (nombre) values ('Fitness');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Seafood');
insert into A_TIPO_PRODUCTO (nombre) values ('Home');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Frozen Foods');
insert into A_TIPO_PRODUCTO (nombre) values ('Beauty');
insert into A_TIPO_PRODUCTO (nombre) values ('Home');
insert into A_TIPO_PRODUCTO (nombre) values ('Office');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Condiments');
insert into A_TIPO_PRODUCTO (nombre) values ('Books');
insert into A_TIPO_PRODUCTO (nombre) values ('Kitchen');
insert into A_TIPO_PRODUCTO (nombre) values ('Kitchen');
insert into A_TIPO_PRODUCTO (nombre) values ('Office');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Seafood');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Vegetables');
insert into A_TIPO_PRODUCTO (nombre) values ('Home');
insert into A_TIPO_PRODUCTO (nombre) values ('Toys');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Snacks');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Salads');
insert into A_TIPO_PRODUCTO (nombre) values ('Fitness');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Snacks');
insert into A_TIPO_PRODUCTO (nombre) values ('Outdoor');
insert into A_TIPO_PRODUCTO (nombre) values ('Pets');
insert into A_TIPO_PRODUCTO (nombre) values ('Kitchen');
insert into A_TIPO_PRODUCTO (nombre) values ('Accessories');
insert into A_TIPO_PRODUCTO (nombre) values ('Smart Home');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Cereals');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Vegetables');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Prepared Meals');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Produce');
insert into A_TIPO_PRODUCTO (nombre) values ('Pets');
insert into A_TIPO_PRODUCTO (nombre) values ('Clothing - Outerwear');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Frozen Foods');
insert into A_TIPO_PRODUCTO (nombre) values ('Health');
insert into A_TIPO_PRODUCTO (nombre) values ('Wearable Tech');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Condiments');
insert into A_TIPO_PRODUCTO (nombre) values ('Health');
insert into A_TIPO_PRODUCTO (nombre) values ('Clothing - Accessories');
insert into A_TIPO_PRODUCTO (nombre) values ('Automotive');
insert into A_TIPO_PRODUCTO (nombre) values ('Outdoor');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Household');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Freezer');
insert into A_TIPO_PRODUCTO (nombre) values ('Fitness');
insert into A_TIPO_PRODUCTO (nombre) values ('Home');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Salads');
insert into A_TIPO_PRODUCTO (nombre) values ('Kitchen');
insert into A_TIPO_PRODUCTO (nombre) values ('Kitchen');
insert into A_TIPO_PRODUCTO (nombre) values ('Outdoor');
insert into A_TIPO_PRODUCTO (nombre) values ('Automotive');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Canned Goods');
insert into A_TIPO_PRODUCTO (nombre) values ('Clothing - Tops');
insert into A_TIPO_PRODUCTO (nombre) values ('Clothing - Dresses');
insert into A_TIPO_PRODUCTO (nombre) values ('Accessories');
insert into A_TIPO_PRODUCTO (nombre) values ('Home Appliances');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Frozen Foods');
insert into A_TIPO_PRODUCTO (nombre) values ('Outdoor');
insert into A_TIPO_PRODUCTO (nombre) values ('Garden');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Snacks');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Condiments');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Produce');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Condiments');
insert into A_TIPO_PRODUCTO (nombre) values ('Kitchen');
insert into A_TIPO_PRODUCTO (nombre) values ('Beauty');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Canned Goods');
insert into A_TIPO_PRODUCTO (nombre) values ('Toys');
insert into A_TIPO_PRODUCTO (nombre) values ('Audio');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Produce');
insert into A_TIPO_PRODUCTO (nombre) values ('Kitchen');
insert into A_TIPO_PRODUCTO (nombre) values ('Garden');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Dairy');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Baking Goods');
insert into A_TIPO_PRODUCTO (nombre) values ('Pets');
insert into A_TIPO_PRODUCTO (nombre) values ('Accessories');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Condiments');
insert into A_TIPO_PRODUCTO (nombre) values ('Home');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Meat');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Baking');
insert into A_TIPO_PRODUCTO (nombre) values ('Clothing - Footwear');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Frozen Foods');
insert into A_TIPO_PRODUCTO (nombre) values ('Office');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Produce');
insert into A_TIPO_PRODUCTO (nombre) values ('Home');
insert into A_TIPO_PRODUCTO (nombre) values ('Electronics');
insert into A_TIPO_PRODUCTO (nombre) values ('Art Supplies');
insert into A_TIPO_PRODUCTO (nombre) values ('Health');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Frozen Foods');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Snacks');
insert into A_TIPO_PRODUCTO (nombre) values ('Crafts');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Beverages');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Canned Goods');
insert into A_TIPO_PRODUCTO (nombre) values ('Kitchen');
insert into A_TIPO_PRODUCTO (nombre) values ('Clothing - Bottoms');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Grains');
insert into A_TIPO_PRODUCTO (nombre) values ('Outdoor');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Breakfast');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Snacks');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Grains');
insert into A_TIPO_PRODUCTO (nombre) values ('Home');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Bakery');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Snacks');
insert into A_TIPO_PRODUCTO (nombre) values ('Clothing - Activewear');
insert into A_TIPO_PRODUCTO (nombre) values ('Clothing - Tops');
insert into A_TIPO_PRODUCTO (nombre) values ('Kitchen');
insert into A_TIPO_PRODUCTO (nombre) values ('Office');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Condiments');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Condiments');
insert into A_TIPO_PRODUCTO (nombre) values ('Garden');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Fruits');
insert into A_TIPO_PRODUCTO (nombre) values ('Outdoor');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Frozen Foods');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Condiments');
insert into A_TIPO_PRODUCTO (nombre) values ('Garden');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Baking');
insert into A_TIPO_PRODUCTO (nombre) values ('Kitchen');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Snacks');
insert into A_TIPO_PRODUCTO (nombre) values ('Health');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Breakfast');
insert into A_TIPO_PRODUCTO (nombre) values ('Food');
insert into A_TIPO_PRODUCTO (nombre) values ('Fitness');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Breakfast');
insert into A_TIPO_PRODUCTO (nombre) values ('Clothing - Accessories');
insert into A_TIPO_PRODUCTO (nombre) values ('Pets');
insert into A_TIPO_PRODUCTO (nombre) values ('Pets');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Snacks');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Condiments');
insert into A_TIPO_PRODUCTO (nombre) values ('Gaming');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Beverages');
insert into A_TIPO_PRODUCTO (nombre) values ('Automotive');
insert into A_TIPO_PRODUCTO (nombre) values ('Art Supplies');
insert into A_TIPO_PRODUCTO (nombre) values ('Outdoor');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Snacks');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Beverages');
insert into A_TIPO_PRODUCTO (nombre) values ('Garden');
insert into A_TIPO_PRODUCTO (nombre) values ('Art Supplies');
insert into A_TIPO_PRODUCTO (nombre) values ('Fitness');
insert into A_TIPO_PRODUCTO (nombre) values ('Office');
insert into A_TIPO_PRODUCTO (nombre) values ('Health');
insert into A_TIPO_PRODUCTO (nombre) values ('Electronics');
insert into A_TIPO_PRODUCTO (nombre) values ('Home');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Breakfast');
insert into A_TIPO_PRODUCTO (nombre) values ('Electronics');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Snacks');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Condiments');
insert into A_TIPO_PRODUCTO (nombre) values ('Home Appliances');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Frozen Foods');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Frozen');
insert into A_TIPO_PRODUCTO (nombre) values ('Pets');
insert into A_TIPO_PRODUCTO (nombre) values ('Kitchen');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Condiments');
insert into A_TIPO_PRODUCTO (nombre) values ('Kitchen');
insert into A_TIPO_PRODUCTO (nombre) values ('Toys');
insert into A_TIPO_PRODUCTO (nombre) values ('Kitchen');
insert into A_TIPO_PRODUCTO (nombre) values ('Kitchen');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Produce');
insert into A_TIPO_PRODUCTO (nombre) values ('Health');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Sides');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Canned Goods');
insert into A_TIPO_PRODUCTO (nombre) values ('Kitchen');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Bakery');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Produce');
insert into A_TIPO_PRODUCTO (nombre) values ('Accessories');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Fruits');
insert into A_TIPO_PRODUCTO (nombre) values ('Fitness');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Snacks');
insert into A_TIPO_PRODUCTO (nombre) values ('Clothing - Activewear');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Dairy');
insert into A_TIPO_PRODUCTO (nombre) values ('Office');
insert into A_TIPO_PRODUCTO (nombre) values ('Automotive');
insert into A_TIPO_PRODUCTO (nombre) values ('Toys');
insert into A_TIPO_PRODUCTO (nombre) values ('Fitness');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Condiments');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Spices');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Snacks');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Meat Substitutes');
insert into A_TIPO_PRODUCTO (nombre) values ('Automotive');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Meat');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Beverages');
insert into A_TIPO_PRODUCTO (nombre) values ('Pets');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Frozen Foods');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Frozen');
insert into A_TIPO_PRODUCTO (nombre) values ('Garden');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Snacks');
insert into A_TIPO_PRODUCTO (nombre) values ('Office');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Breakfast');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Canned Goods');
insert into A_TIPO_PRODUCTO (nombre) values ('Home');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Frozen Fruits');
insert into A_TIPO_PRODUCTO (nombre) values ('Crafts');
insert into A_TIPO_PRODUCTO (nombre) values ('Outdoor');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Beverages');
insert into A_TIPO_PRODUCTO (nombre) values ('Accessories');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Dairy');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Meat & Seafood');
insert into A_TIPO_PRODUCTO (nombre) values ('Clothing - Outerwear');
insert into A_TIPO_PRODUCTO (nombre) values ('Footwear');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Snacks');
insert into A_TIPO_PRODUCTO (nombre) values ('Kitchen');
insert into A_TIPO_PRODUCTO (nombre) values ('Travel');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Prepared Foods');
insert into A_TIPO_PRODUCTO (nombre) values ('Toys');
insert into A_TIPO_PRODUCTO (nombre) values ('Health');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Pasta');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Fruits');
insert into A_TIPO_PRODUCTO (nombre) values ('Electronics');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Frozen Foods');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Canned Soups');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Produce');
insert into A_TIPO_PRODUCTO (nombre) values ('Electronics');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Snacks');
insert into A_TIPO_PRODUCTO (nombre) values ('Toys');
insert into A_TIPO_PRODUCTO (nombre) values ('Kitchen');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Pasta');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Snacks');
insert into A_TIPO_PRODUCTO (nombre) values ('Garden');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Vegetarian');
insert into A_TIPO_PRODUCTO (nombre) values ('Pets');
insert into A_TIPO_PRODUCTO (nombre) values ('Office');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Nuts');
insert into A_TIPO_PRODUCTO (nombre) values ('Kitchen');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Bakery');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Snacks');
insert into A_TIPO_PRODUCTO (nombre) values ('Automotive');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Fresh Produce');
insert into A_TIPO_PRODUCTO (nombre) values ('Kitchen');
insert into A_TIPO_PRODUCTO (nombre) values ('Health');
insert into A_TIPO_PRODUCTO (nombre) values ('Kitchen');
insert into A_TIPO_PRODUCTO (nombre) values ('Health');
insert into A_TIPO_PRODUCTO (nombre) values ('Beauty');
insert into A_TIPO_PRODUCTO (nombre) values ('Kitchen');
insert into A_TIPO_PRODUCTO (nombre) values ('Kitchen');
insert into A_TIPO_PRODUCTO (nombre) values ('Health');
insert into A_TIPO_PRODUCTO (nombre) values ('Outdoor');
insert into A_TIPO_PRODUCTO (nombre) values ('Kitchen');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Bakery');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Snacks');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Meat');
insert into A_TIPO_PRODUCTO (nombre) values ('Clothing - Dresses');
insert into A_TIPO_PRODUCTO (nombre) values ('Smart Home');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Frozen');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Frozen Foods');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Seafood');
insert into A_TIPO_PRODUCTO (nombre) values ('Kitchen');
insert into A_TIPO_PRODUCTO (nombre) values ('Kitchen');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Canned Goods');
insert into A_TIPO_PRODUCTO (nombre) values ('Outdoor');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Bakery');
insert into A_TIPO_PRODUCTO (nombre) values ('Crafts');
insert into A_TIPO_PRODUCTO (nombre) values ('Health');
insert into A_TIPO_PRODUCTO (nombre) values ('Home');
insert into A_TIPO_PRODUCTO (nombre) values ('Art Supplies');
insert into A_TIPO_PRODUCTO (nombre) values ('Pets');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Condiments');
insert into A_TIPO_PRODUCTO (nombre) values ('Fitness');
insert into A_TIPO_PRODUCTO (nombre) values ('Toys');
insert into A_TIPO_PRODUCTO (nombre) values ('Kitchen');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Sides');
insert into A_TIPO_PRODUCTO (nombre) values ('Kitchen');
insert into A_TIPO_PRODUCTO (nombre) values ('Pets');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Frozen');
insert into A_TIPO_PRODUCTO (nombre) values ('Outdoor');
insert into A_TIPO_PRODUCTO (nombre) values ('Home');
insert into A_TIPO_PRODUCTO (nombre) values ('Kitchen');
insert into A_TIPO_PRODUCTO (nombre) values ('Crafts');
insert into A_TIPO_PRODUCTO (nombre) values ('Home');
insert into A_TIPO_PRODUCTO (nombre) values ('Health');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Condiments');
insert into A_TIPO_PRODUCTO (nombre) values ('Toys');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Pasta');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Bakery');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Baking & Cooking');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Salads');
insert into A_TIPO_PRODUCTO (nombre) values ('Kitchen');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Snacks');
insert into A_TIPO_PRODUCTO (nombre) values ('Fitness');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Canned Goods');
insert into A_TIPO_PRODUCTO (nombre) values ('Clothing - Dresses');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Snacks');
insert into A_TIPO_PRODUCTO (nombre) values ('Art Supplies');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Soups');
insert into A_TIPO_PRODUCTO (nombre) values ('Clothing');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Snacks');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Produce');
insert into A_TIPO_PRODUCTO (nombre) values ('Beauty');
insert into A_TIPO_PRODUCTO (nombre) values ('Health');
insert into A_TIPO_PRODUCTO (nombre) values ('Garden');
insert into A_TIPO_PRODUCTO (nombre) values ('Health');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Frozen Foods');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Fruits');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Condiments');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Condiments');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Beverages');
insert into A_TIPO_PRODUCTO (nombre) values ('Garden');
insert into A_TIPO_PRODUCTO (nombre) values ('Clothing - Outerwear');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Dips');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Vegetables');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Snacks');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Snacks');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Frozen Vegetables');
insert into A_TIPO_PRODUCTO (nombre) values ('Books');
insert into A_TIPO_PRODUCTO (nombre) values ('Home');
insert into A_TIPO_PRODUCTO (nombre) values ('Travel');
insert into A_TIPO_PRODUCTO (nombre) values ('Health');
insert into A_TIPO_PRODUCTO (nombre) values ('Art Supplies');
insert into A_TIPO_PRODUCTO (nombre) values ('Fitness');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Canned Goods');
insert into A_TIPO_PRODUCTO (nombre) values ('Kitchen');
insert into A_TIPO_PRODUCTO (nombre) values ('Toys');
insert into A_TIPO_PRODUCTO (nombre) values ('Electronics');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Snacks');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Condiments');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Produce');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Condiments');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Pantry');
insert into A_TIPO_PRODUCTO (nombre) values ('Garden');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Snacks');
insert into A_TIPO_PRODUCTO (nombre) values ('Office');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Canned Goods');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Dairy');
insert into A_TIPO_PRODUCTO (nombre) values ('Outdoor');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Bakery');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Prepared Foods');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Condiments');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Condiments');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Snacks');
insert into A_TIPO_PRODUCTO (nombre) values ('Health');
insert into A_TIPO_PRODUCTO (nombre) values ('Home Appliances');
insert into A_TIPO_PRODUCTO (nombre) values ('Beauty');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Condiments');
insert into A_TIPO_PRODUCTO (nombre) values ('Kitchen');
insert into A_TIPO_PRODUCTO (nombre) values ('Clothing');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Seafood');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Snacks');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Snacks');
insert into A_TIPO_PRODUCTO (nombre) values ('Kitchen');
insert into A_TIPO_PRODUCTO (nombre) values ('Beauty');
insert into A_TIPO_PRODUCTO (nombre) values ('Clothing - Bottoms');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Snacks');
insert into A_TIPO_PRODUCTO (nombre) values ('Automotive');
insert into A_TIPO_PRODUCTO (nombre) values ('Clothing - Tops');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Canned Goods');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Dips');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Sides');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Salads');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Condiments');
insert into A_TIPO_PRODUCTO (nombre) values ('Toys');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Frozen Desserts');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Frozen Foods');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Condiments');
insert into A_TIPO_PRODUCTO (nombre) values ('Outdoor');
insert into A_TIPO_PRODUCTO (nombre) values ('Outdoor');
insert into A_TIPO_PRODUCTO (nombre) values ('Home');
insert into A_TIPO_PRODUCTO (nombre) values ('Outdoor');
insert into A_TIPO_PRODUCTO (nombre) values ('Books');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Vegetables');
insert into A_TIPO_PRODUCTO (nombre) values ('Clothing - Outerwear');
insert into A_TIPO_PRODUCTO (nombre) values ('Garden');
insert into A_TIPO_PRODUCTO (nombre) values ('Music');
insert into A_TIPO_PRODUCTO (nombre) values ('Outdoor');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Condiments');
insert into A_TIPO_PRODUCTO (nombre) values ('Kitchen');
insert into A_TIPO_PRODUCTO (nombre) values ('Kitchen');
insert into A_TIPO_PRODUCTO (nombre) values ('Health');
insert into A_TIPO_PRODUCTO (nombre) values ('Kitchen');
insert into A_TIPO_PRODUCTO (nombre) values ('Home');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Grains');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Sauces');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Meat');
insert into A_TIPO_PRODUCTO (nombre) values ('Office');
insert into A_TIPO_PRODUCTO (nombre) values ('Home');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Canned Goods');
insert into A_TIPO_PRODUCTO (nombre) values ('Kitchen');
insert into A_TIPO_PRODUCTO (nombre) values ('Health');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Soups');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Oils');
insert into A_TIPO_PRODUCTO (nombre) values ('Outdoor');
insert into A_TIPO_PRODUCTO (nombre) values ('Crafts');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Frozen Meals');
insert into A_TIPO_PRODUCTO (nombre) values ('Electronics');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Grains');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Cooking Oils');
insert into A_TIPO_PRODUCTO (nombre) values ('Art Supplies');
insert into A_TIPO_PRODUCTO (nombre) values ('Fitness');
insert into A_TIPO_PRODUCTO (nombre) values ('Toys');
insert into A_TIPO_PRODUCTO (nombre) values ('Kitchen');
insert into A_TIPO_PRODUCTO (nombre) values ('Photography');
insert into A_TIPO_PRODUCTO (nombre) values ('Electronics');
insert into A_TIPO_PRODUCTO (nombre) values ('Pets');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Snacks');
insert into A_TIPO_PRODUCTO (nombre) values ('Electronics');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Vegetables');
insert into A_TIPO_PRODUCTO (nombre) values ('Accessories');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Fruits');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Snacks');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Snacks');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Condiments');
insert into A_TIPO_PRODUCTO (nombre) values ('Pets');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Produce');
insert into A_TIPO_PRODUCTO (nombre) values ('Tools');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Frozen Foods');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Bakery');
insert into A_TIPO_PRODUCTO (nombre) values ('Clothing - Tops');
insert into A_TIPO_PRODUCTO (nombre) values ('Office');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Snacks');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Snacks');
insert into A_TIPO_PRODUCTO (nombre) values ('Health');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Bakery');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Beverages');
insert into A_TIPO_PRODUCTO (nombre) values ('Electronics');
insert into A_TIPO_PRODUCTO (nombre) values ('Outdoor');
insert into A_TIPO_PRODUCTO (nombre) values ('Home');
insert into A_TIPO_PRODUCTO (nombre) values ('Travel');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Canned Goods');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Frozen Foods');
insert into A_TIPO_PRODUCTO (nombre) values ('Toys');
insert into A_TIPO_PRODUCTO (nombre) values ('Clothing - Footwear');
insert into A_TIPO_PRODUCTO (nombre) values ('Outdoor');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Condiments');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Snacks');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Frozen Foods');
insert into A_TIPO_PRODUCTO (nombre) values ('Outdoor');
insert into A_TIPO_PRODUCTO (nombre) values ('Outdoor');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Condiments');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Salads');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Frozen Foods');
insert into A_TIPO_PRODUCTO (nombre) values ('Home Appliances');
insert into A_TIPO_PRODUCTO (nombre) values ('Pets');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Produce');
insert into A_TIPO_PRODUCTO (nombre) values ('Kitchen');
insert into A_TIPO_PRODUCTO (nombre) values ('Outdoor');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Frozen Foods');
insert into A_TIPO_PRODUCTO (nombre) values ('Garden');
insert into A_TIPO_PRODUCTO (nombre) values ('Home Improvement');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Nuts');
insert into A_TIPO_PRODUCTO (nombre) values ('Toys');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Snacks');
insert into A_TIPO_PRODUCTO (nombre) values ('Kitchen');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Meat');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Dairy');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Snacks');
insert into A_TIPO_PRODUCTO (nombre) values ('Accessories');
insert into A_TIPO_PRODUCTO (nombre) values ('Clothing - Tops');
insert into A_TIPO_PRODUCTO (nombre) values ('Home');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Bakery');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Snacks');
insert into A_TIPO_PRODUCTO (nombre) values ('Photography');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Spices & Seasonings');
insert into A_TIPO_PRODUCTO (nombre) values ('Home');
insert into A_TIPO_PRODUCTO (nombre) values ('Health');
insert into A_TIPO_PRODUCTO (nombre) values ('Kitchen');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Deli Meats');
insert into A_TIPO_PRODUCTO (nombre) values ('Home');
insert into A_TIPO_PRODUCTO (nombre) values ('Home');
insert into A_TIPO_PRODUCTO (nombre) values ('Home');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Beverages');
insert into A_TIPO_PRODUCTO (nombre) values ('Computers');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Snacks');
insert into A_TIPO_PRODUCTO (nombre) values ('Health');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Pasta');
insert into A_TIPO_PRODUCTO (nombre) values ('Travel');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Breakfast');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Snacks');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Breakfast');
insert into A_TIPO_PRODUCTO (nombre) values ('Office');
insert into A_TIPO_PRODUCTO (nombre) values ('Kitchen');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Bakery');
insert into A_TIPO_PRODUCTO (nombre) values ('Electronics');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Frozen Desserts');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Condiments');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Confectionery');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Meat');
insert into A_TIPO_PRODUCTO (nombre) values ('Safety');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Vegetable');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Produce');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Condiments');
insert into A_TIPO_PRODUCTO (nombre) values ('Outdoor');
insert into A_TIPO_PRODUCTO (nombre) values ('Outdoor');
insert into A_TIPO_PRODUCTO (nombre) values ('Kitchen');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Canned Goods');
insert into A_TIPO_PRODUCTO (nombre) values ('Photography');
insert into A_TIPO_PRODUCTO (nombre) values ('Clothing - Pants');
insert into A_TIPO_PRODUCTO (nombre) values ('Accessories');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Produce');
insert into A_TIPO_PRODUCTO (nombre) values ('Pets');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Nuts');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Grains');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Nut Butters');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Snacks');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Frozen Foods');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Vegetables');
insert into A_TIPO_PRODUCTO (nombre) values ('Office');
insert into A_TIPO_PRODUCTO (nombre) values ('Clothing - Footwear');
insert into A_TIPO_PRODUCTO (nombre) values ('Kitchen');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Condiments');
insert into A_TIPO_PRODUCTO (nombre) values ('Home');
insert into A_TIPO_PRODUCTO (nombre) values ('Office');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Canned Goods');
insert into A_TIPO_PRODUCTO (nombre) values ('Accessories');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Frozen Desserts');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Snacks');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Snacks');
insert into A_TIPO_PRODUCTO (nombre) values ('Home');
insert into A_TIPO_PRODUCTO (nombre) values ('Office');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Frozen Desserts');
insert into A_TIPO_PRODUCTO (nombre) values ('Health');
insert into A_TIPO_PRODUCTO (nombre) values ('Electronics');
insert into A_TIPO_PRODUCTO (nombre) values ('Travel');
insert into A_TIPO_PRODUCTO (nombre) values ('Outdoor');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Condiments');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Breakfast');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Nuts');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Breakfast');
insert into A_TIPO_PRODUCTO (nombre) values ('Home');
insert into A_TIPO_PRODUCTO (nombre) values ('Outdoor');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Sauces');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Canned Goods');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Beverages');
insert into A_TIPO_PRODUCTO (nombre) values ('Pets');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Snacks');
insert into A_TIPO_PRODUCTO (nombre) values ('Outdoor');
insert into A_TIPO_PRODUCTO (nombre) values ('Clothing - Loungewear');
insert into A_TIPO_PRODUCTO (nombre) values ('Outdoor');
insert into A_TIPO_PRODUCTO (nombre) values ('Electronics');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Beverages');
insert into A_TIPO_PRODUCTO (nombre) values ('Fitness');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Dips');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Frozen Foods');
insert into A_TIPO_PRODUCTO (nombre) values ('Office');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Fresh Produce');
insert into A_TIPO_PRODUCTO (nombre) values ('Toys');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Breakfast');
insert into A_TIPO_PRODUCTO (nombre) values ('Home');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Canned Goods');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Produce');
insert into A_TIPO_PRODUCTO (nombre) values ('Pets');
insert into A_TIPO_PRODUCTO (nombre) values ('Accessories');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Meat');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Grains');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Baking Goods');
insert into A_TIPO_PRODUCTO (nombre) values ('Pets');
insert into A_TIPO_PRODUCTO (nombre) values ('Electronics');
insert into A_TIPO_PRODUCTO (nombre) values ('Health');
insert into A_TIPO_PRODUCTO (nombre) values ('Automotive');
insert into A_TIPO_PRODUCTO (nombre) values ('Kitchen');
insert into A_TIPO_PRODUCTO (nombre) values ('Clothing - Shirts');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Grocery');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Frozen Foods');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Snacks');
insert into A_TIPO_PRODUCTO (nombre) values ('Clothing - Outerwear');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Baking');
insert into A_TIPO_PRODUCTO (nombre) values ('Clothing - Shoes');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Frozen Foods');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Beverages');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Baking');
insert into A_TIPO_PRODUCTO (nombre) values ('Clothing - Accessories');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Breakfast');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Sides');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Dairy');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Pasta');
insert into A_TIPO_PRODUCTO (nombre) values ('Electronics');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Dried Fruits');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Frozen Meals');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Frozen');
insert into A_TIPO_PRODUCTO (nombre) values ('Home');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Beverages');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Condiments');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Produce');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Salads');
insert into A_TIPO_PRODUCTO (nombre) values ('Pets');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Dairy');
insert into A_TIPO_PRODUCTO (nombre) values ('Music');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Condiments');
insert into A_TIPO_PRODUCTO (nombre) values ('Safety');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Produce');
insert into A_TIPO_PRODUCTO (nombre) values ('Home');
insert into A_TIPO_PRODUCTO (nombre) values ('Kitchen');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Soups');
insert into A_TIPO_PRODUCTO (nombre) values ('Wearable Tech');
insert into A_TIPO_PRODUCTO (nombre) values ('Home Appliances');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Snacks');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Breakfast');
insert into A_TIPO_PRODUCTO (nombre) values ('Garden');
insert into A_TIPO_PRODUCTO (nombre) values ('Food');
insert into A_TIPO_PRODUCTO (nombre) values ('Photography');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Produce');
insert into A_TIPO_PRODUCTO (nombre) values ('Tools');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Bakery');
insert into A_TIPO_PRODUCTO (nombre) values ('Outdoor');
insert into A_TIPO_PRODUCTO (nombre) values ('Home');
insert into A_TIPO_PRODUCTO (nombre) values ('Music');
insert into A_TIPO_PRODUCTO (nombre) values ('Toys');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Frozen Desserts');
insert into A_TIPO_PRODUCTO (nombre) values ('Outdoor');
insert into A_TIPO_PRODUCTO (nombre) values ('Garden');
insert into A_TIPO_PRODUCTO (nombre) values ('Pets');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Prepared Foods');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Spices');
insert into A_TIPO_PRODUCTO (nombre) values ('Health');
insert into A_TIPO_PRODUCTO (nombre) values ('Electronics');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Frozen Foods');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Condiments');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Beverages');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Produce');
insert into A_TIPO_PRODUCTO (nombre) values ('Electronics');
insert into A_TIPO_PRODUCTO (nombre) values ('Office');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Dairy Alternatives');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Sauces');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Baking');
insert into A_TIPO_PRODUCTO (nombre) values ('Outdoor');
insert into A_TIPO_PRODUCTO (nombre) values ('Kitchen');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Breakfast');
insert into A_TIPO_PRODUCTO (nombre) values ('Accessories');
insert into A_TIPO_PRODUCTO (nombre) values ('Electronics');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Condiments');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Salads');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Snacks');
insert into A_TIPO_PRODUCTO (nombre) values ('Home');
insert into A_TIPO_PRODUCTO (nombre) values ('Accessories');
insert into A_TIPO_PRODUCTO (nombre) values ('Pets');
insert into A_TIPO_PRODUCTO (nombre) values ('Books');
insert into A_TIPO_PRODUCTO (nombre) values ('Fitness');
insert into A_TIPO_PRODUCTO (nombre) values ('Fitness');
insert into A_TIPO_PRODUCTO (nombre) values ('Outdoor');
insert into A_TIPO_PRODUCTO (nombre) values ('Fitness');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Beverages');
insert into A_TIPO_PRODUCTO (nombre) values ('Home');
insert into A_TIPO_PRODUCTO (nombre) values ('Clothing - Activewear');
insert into A_TIPO_PRODUCTO (nombre) values ('Pets');
insert into A_TIPO_PRODUCTO (nombre) values ('Clothing - Outerwear');
insert into A_TIPO_PRODUCTO (nombre) values ('Bicycles');
insert into A_TIPO_PRODUCTO (nombre) values ('Kitchen');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Snacks');
insert into A_TIPO_PRODUCTO (nombre) values ('Garden');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Dairy');
insert into A_TIPO_PRODUCTO (nombre) values ('Smart Home');
insert into A_TIPO_PRODUCTO (nombre) values ('Storage');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Condiments');
insert into A_TIPO_PRODUCTO (nombre) values ('Kitchen');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Pasta');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Condiments');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Condiments');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Freezer');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Salads');
insert into A_TIPO_PRODUCTO (nombre) values ('Kitchen');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Prepared Foods');
insert into A_TIPO_PRODUCTO (nombre) values ('Health');
insert into A_TIPO_PRODUCTO (nombre) values ('Clothing - Footwear');
insert into A_TIPO_PRODUCTO (nombre) values ('Kitchen');
insert into A_TIPO_PRODUCTO (nombre) values ('Toys');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Beverages');
insert into A_TIPO_PRODUCTO (nombre) values ('Home');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Bakery');
insert into A_TIPO_PRODUCTO (nombre) values ('Clothing - Activewear');
insert into A_TIPO_PRODUCTO (nombre) values ('Home');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Frozen Foods');
insert into A_TIPO_PRODUCTO (nombre) values ('Storage');
insert into A_TIPO_PRODUCTO (nombre) values ('Electronics');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Nuts');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Dairy');
insert into A_TIPO_PRODUCTO (nombre) values ('Fitness');
insert into A_TIPO_PRODUCTO (nombre) values ('Pets');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Canned Goods');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Prepared Foods');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Salad Toppings');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Canned Goods');
insert into A_TIPO_PRODUCTO (nombre) values ('Audio');
insert into A_TIPO_PRODUCTO (nombre) values ('Automotive');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Snacks');
insert into A_TIPO_PRODUCTO (nombre) values ('Outdoor');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Grains');
insert into A_TIPO_PRODUCTO (nombre) values ('Kitchen');
insert into A_TIPO_PRODUCTO (nombre) values ('Clothing - Outerwear');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Frozen Foods');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Salads');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Snacks');
insert into A_TIPO_PRODUCTO (nombre) values ('Kitchen');
insert into A_TIPO_PRODUCTO (nombre) values ('Fitness');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Bakery');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Breakfast Foods');
insert into A_TIPO_PRODUCTO (nombre) values ('Kitchen');
insert into A_TIPO_PRODUCTO (nombre) values ('Gaming');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Salads');
insert into A_TIPO_PRODUCTO (nombre) values ('Travel');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Snacks');
insert into A_TIPO_PRODUCTO (nombre) values ('Health');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Pasta');
insert into A_TIPO_PRODUCTO (nombre) values ('Smart Home');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Meat');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Pantry');
insert into A_TIPO_PRODUCTO (nombre) values ('Kitchen');
insert into A_TIPO_PRODUCTO (nombre) values ('Clothing - Bottoms');
insert into A_TIPO_PRODUCTO (nombre) values ('Office');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Frozen Foods');
insert into A_TIPO_PRODUCTO (nombre) values ('Safety');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Snacks');
insert into A_TIPO_PRODUCTO (nombre) values ('Health');
insert into A_TIPO_PRODUCTO (nombre) values ('Toys');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Bakery');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Grains');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Condiments');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Sauces');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Breakfast');
insert into A_TIPO_PRODUCTO (nombre) values ('Home');
insert into A_TIPO_PRODUCTO (nombre) values ('Computers');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Protein');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Seafood');
insert into A_TIPO_PRODUCTO (nombre) values ('Kitchen');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Baking Goods');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Produce');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Baking Goods');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Snacks');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Meat');
insert into A_TIPO_PRODUCTO (nombre) values ('Fitness');
insert into A_TIPO_PRODUCTO (nombre) values ('Kitchen');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Salads');
insert into A_TIPO_PRODUCTO (nombre) values ('Food - Breakfast');
insert into A_TIPO_PRODUCTO (nombre) values ('Accessories');
insert into A_TIPO_PRODUCTO (nombre) values ('Home');
insert into A_TIPO_PRODUCTO (nombre) values ('Photography');
insert into A_TIPO_PRODUCTO (nombre) values ('Audio');
insert into A_TIPO_PRODUCTO (nombre) values ('Outdoor');
insert into A_TIPO_PRODUCTO (nombre) values ('Office');
insert into A_TIPO_PRODUCTO (nombre) values ('Smart Home');
insert into A_TIPO_PRODUCTO (nombre) values ('Pets');
